# Generated by Django 5.1.1 on 2024-10-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_todolist_delete_todoitem_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateOfCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='studentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('hours', models.FloatField(max_length=10)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dateofcleanup')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
