# Generated by Django 5.1.1 on 2024-10-18 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dateofcleanup_studentinformation_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('idNum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('school', models.CharField(max_length=100)),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.DeleteModel(
            name='studentInformation',
        ),
    ]
