# Generated by Django 5.1.1 on 2025-03-11 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentinformationmodel_delete_studentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformationmodel',
            name='hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentinformationmodel',
            name='idNum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
